name = "shopinid"
compatibility_date = "2024-03-04"
pages_build_output_dir = "./dist"

# NODEJS COMPABILITY
compatibility_flags = [ "nodejs_compat" ]

# [BACA] Binding untuk Cloudflare KV (Smart Caching)
# Gunakan command: npx wrangler kv:namespace create "CACHE_KV"
[[kv_namespaces]]
binding = "CACHE_KV"
id = "8971a02eedf043389dfcd9015c02def9"

# [BACA] Binding untuk Cloudflare D1 (Database SQL)
# Gunakan command: npx wrangler d1 create premium-store-db
[[d1_databases]]
binding = "DB"
database_name = "shopinid"
database_id = "12479d96-5818-4b80-9760-32e439aa5bb6"
migrations_dir = "d1/migrations"
